name: Build Flatpak

on:
  # Enable manual run
  workflow_dispatch:
  pull_request:

env:
  project-id: codes.merritt.FeelingFinder

jobs:
  build-flutter-app:
    name: Build and compressed Flutter app
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Flutter dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libx11-dev pkg-config cmake ninja-build libblkid-dev
      - name: Setup Flutter
        uses: subosito/flutter-action@v2

      - name: Build Flutter linux version
        working-directory: ${{ github.workspace }}
        run: |
          ./build-flutter-app.sh
      - name: Upload app archive to workflow
        uses: actions/upload-artifact@v3
        with:
          name: FlutterApp-Archive
          path: photon/FlutterApp-Linux-Portable.tar.gz

  build-flatpak:
    name: Build flatpak
    needs: build-flutter-app
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:freedesktop-22.08
      options: --privileged
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build .flatpak
        uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v5
        with:
          bundle: FlutterApp.flatpak
          manifest-path: flathub_repo/com.example.FlutterApp.yml

      - name: Upload .flatpak artifact to workflow
        uses: actions/upload-artifact@v3
        with:
          name: Flatpak artifact
          path: FlutterApp.flatpak
